### ISSUE TITLE
Web server spawn

### ISSUE THREAD

**Issue by madroots** [Kussie/startpage#2]
Hello, 

thank you for this fork, its really nice. I love it. 

What I do is I add **docker-compose.yml** to the root folder of the project with this content:

```
version: "3"

services:
    client:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - .:/usr/share/nginx/html
```
`docker-compose up -d` will then spawn nginx server on localhost:8000 and you can set this up on a browser new tab with extension like Custom New Tab Page or similar.
